apiVersion: v2
name: wanderer
description: Self-hosted trail database and route planner for hiking, biking and other outdoor activities
type: application
version: 0.1.0
home: https://wanderer.to/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=docker.io/flomp/wanderer-web
appVersion: 'v0.20.0'
dependencies:
  - name: common
    version: 5.1.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
