apiVersion: v2
name: ghostfolio
description: Open source wealth management software
type: application
version: 0.38.0
home: https://ghostfol.io/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=docker.io/ghostfolio/ghostfolio
appVersion: '3.66.0'
dependencies:
  - name: common
    version: 5.1.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: redis
    version: 0.34.26
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
