{{- define "hardcoded" -}}

{{ if and .Values.cnpg.enabled .Values.postgres.enabled }}
{{ fail "postgres cannot be used via chart and CNPG"}}
{{- end }}

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    enabled: true
    strategy: RollingUpdate
    containers:
      main:
        image:
          repository: quay.io/invidious/invidious
          tag: {{ .Chart.AppVersion | quote }}
        envFrom:
{{- if not .Values.companionKey.existingSecret }}
          - secretRef:
              identifier: invidious-hmac-key
{{- end }}
{{- if not .Values.hmacKey.existingSecret }}
          - secretRef:
              identifier: invidious-companion-key
{{- end }}
        env:
{{- if .Values.companionKey.existingSecret }}
          INVIDIOUS_INVIDIOUS_COMPANION_KEY:
            secretKeyRef:
              name: invidious-companion-key
              key: key
{{- end }}
{{- if .Values.hmacKey.existingSecret }}
          INVIDIOUS_HMAC_KEY:
            secretKeyRef:
              name: invidious-hmac-key
              key: key
{{- end }}
{{ if .Values.cnpg.enabled }}
          DB_FQDN_URI: 
            secretKeyRef:
              name: {{ .Values.cnpg.clusterName }}-app
              key: fqdn-uri
          INVIDIOUS_DATABASE_URL:
            value: $(DB_FQDN_URI)?sslmode=verify-full&sslrootcert=/certs/ca.crt
            dependsOn: 
              - DB_FQDN_URI
            secretKeyRef:
              name: {{ .Values.cnpg.clusterName }}-app
              key: fqdn-uri
{{- end }}
{{ if .Values.postgres.enabled }}
          INVIDIOUS_DATABASE_URL: 
            value: postgres://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ printf "%s-postgres" .Release.Name }}:5432/{{ .Values.postgres.auth.database }}
{{ end }}
          INVIDIOUS_CONFIG: |
            check_tables: true
            invidious_companion:
              - private_url: "http://{{.Release.Name}}-companion:8282/companion"
{{- if .Values.companion.publicUrl }}
                public_url: {{ .Values.companion.publicUrl }}
{{- end }}
{{ .Values.config | toYaml | indent 12 }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
              drop:
              - ALL
          seccompProfile:
              type: RuntimeDefault
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/stats
                port: 3000
              initialDelaySeconds: 10
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 2
          readiness: *probe
  companion:
    enabled: true
    containers:
      main:
        image:
          repository: quay.io/invidious/invidious-companion
          tag: latest
{{- if .Values.companionKey.existingSecret }}
        env:
          SERVER_SECRET_KEY:
            secretKeyRef:
              name: {{ .Values.companionKey.existingSecret.name }}
              key: {{ .Values.companionKey.existingSecret.key }}
{{- else }}
        envFrom:
          - secretRef:
              identifier: invidious-companion-key
        env:
          SERVER_SECRET_KEY: $(INVIDIOUS_INVIDIOUS_COMPANION_KEY)
{{- end }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
              drop:
              - ALL
          seccompProfile:
              type: RuntimeDefault

service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 3000
        protocol: TCP
  companion:
    controller: companion
    ports:
      http:
        port: 8282
        protocol: TCP

persistence:
  cache:
    advancedMounts:
      main:
        companion:
        - path: /var/tmp/

{{ if .Values.cnpg.enabled }}
  certs:
    type: secret
    name: {{ .Values.cnpg.clusterName }}-ca
    advancedMounts:
      main:
        main:
        - path: /certs/ca.crt
          subPath: ca.crt
{{ end }}

secrets:
  dummy:
    enabled: false
{{- if not .Values.companionKey.existingSecret }}
  invidious-companion-key:
    stringData:
      INVIDIOUS_INVIDIOUS_COMPANION_KEY: {{ .Values.companionKey.value }}
{{- end }}
{{- if not .Values.hmacKey.existingSecret }}
  invidious-hmac-key:
    stringData:
      INVIDIOUS_HMAC_KEY: {{ .Values.hmacKey.value }}
{{- end }}
{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
