# -- Persistent storage configuration
persistence:
  # -- Configuration volume
  config:
    # -- Enable config persistence
    enabled: true
    # -- Config volume size
    size: 15Gi
    # -- Storage access mode
    accessMode: ReadWriteOnce
    # storageClass: gp2

  # -- Transcoding volume
  transcode:
    # -- Enable transcode persistence
    enabled: true
    # -- Transcode volume size
    size: 70Gi
    # -- Storage access mode
    accessMode: ReadWriteOnce
    # storageClass: gp2

  # -- Media library volume
  media:
    # -- Enable media persistence
    enabled: true
    # -- Media volume size
    size: 100Gi
    # -- Storage access mode
    accessMode: ReadWriteOnce
    # storageClass: gp2

# For hardware accel;aration uncomment this
#   dev-dri:
#     enabled: true
#     type: hostPath
#     hostPath: /dev/dri
#     advancedMounts:
#       main:
#         main:
#         - path:  /dev/dri

# defaultPodOptions:
#   securityContext:
#     supplementalGroups: [992]

# Resource limits
# controllers:
#   main:
#     containers:
#       main:
#         resources:
#           requests:
#             cpu: 1000m
#             memory: 1Gi
#           limits:
#             memory: 10Gi
#             cpu: 8000m

# route:
#   main:
#     enabled: true
#     annotations:
#     hostnames:
#       - jellyfin.mydomain
#     parentRefs:
#       - namespace: gateway
#         name: mygateway
#     rules:
#       - matches:
#           - path:
#               type: PathPrefix
#               value: /
#         backendRefs:
#           - name: jellyfin
#             port: 8096
