apiVersion: v2
name: homeassistant
description: Home automation platform with optional LDAP, Matter bridge, and CNPG database support
type: application
version: 1.17.0
# renovate: image=ghcr.io/home-operations/home-assistant
appVersion: '2026.6.1'
home: https://www.home-assistant.io/
sources:
  - https://github.com/swagner-de/charts
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
