apiVersion: v2
name: paperless
description: Document management system with OCR and full-text search
type: application
version: 0.58.0
home: https://docs.paperless-ngx.com/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: '3.0.5'
dependencies:
  - name: common
    version: 5.1.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.20.1
    condition: postgres.enabled
  - name: redis
    version: 0.34.17
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
