apiVersion: v2
name: paperless
description: A Helm chart for Kubernetes
type: application
version: 0.17.7
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: '2.20.1'
dependencies:
  - name: common
    version: 4.4.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.12.4
    condition: postgres.enabled
  - name: redis
    version: 0.16.3
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
