apiVersion: v2
name: mealie
description: A Helm chart for Mealie
type: application
version: 0.1.5

appVersion: "v2.8.0"
dependencies:
  - name: common
    version: 4.3.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 16.6.3
    condition: postgresql.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
