apiVersion: v2
name: mealie
description: A Helm chart for Mealie
type: application
version: 0.10.0
# renovate: image=ghcr.io/mealie-recipes/mealie
appVersion: 'v3.9.1'
dependencies:
  - name: common
    version: 4.5.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.13.6
    condition: postgres.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
