apiVersion: v2
name: mealie
description: Self-hosted recipe manager and meal planner
type: application
version: 0.20.2
home: https://mealie.io/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/mealie-recipes/mealie
appVersion: 'v3.18.0'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.19.5
    condition: postgres.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
