{{- define "hardcoded" -}}

global:
  createDefaultServiceAccount: false

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1883
    runAsGroup: 1883
    fsGroup: 1883
    fsGroupChangePolicy: OnRootMismatch

# Configure options applied to all pods
controllers:
  main:
    containers:
      main:
        enabled: true
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image:
          repository: {{ printf "powerdns/pdns-recursor-%s" (.Chart.AppVersion | replace "." "" | substr 0 2) | quote }}
          tag: {{ .Chart.AppVersion | quote }}
        args:
        - --local-address=0.0.0.0:5353,[::]:5353
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 5353
              initialDelaySeconds: 5
              periodSeconds: 10
          readiness: *probe
          startup: *probe

service:
  main:
    controller: main
    primary: true
    ports:
      dns-tcp:
        port: 53
        protocol: TCP 
        targetPort: 5353
      dns-udp:
        port: 53
        protocol: UDP
        targetPort: 5353

ingress:
  main:
    enabled: false


configMaps:
  config:
    enabled: true
    data:
      recursor.yml: |
{{ .Values.config | toYaml | indent 8 }}


persistence:
  config:
    type: configMap
    identifier: config
    advancedMounts:
      main:
        main:
        - path: /etc/powerdns/

  control:
    type: emptyDir
    advancedMounts:
      main:
        main:
        - path: /var/run/pdns-recursor


{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
