apiVersion: v2
name: dawarich
description: Self-hosted location history tracker and Google Timeline alternative
type: application
version: 0.2.6
home: https://dawarich.app/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=docker.io/freikin/dawarich
appVersion: '1.14.2'
dependencies:
  - name: common
    version: 5.1.0
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: redis
    version: 0.34.26
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
