apiVersion: v2
name: akvorado
description: NetFlow/IPFIX/sFlow collector with ClickHouse analytics
type: application
version: 0.1.3
home: https://github.com/akvorado/akvorado
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/akvorado/akvorado
appVersion: '2.3.0'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
