apiVersion: v2
name: powerdns-recursor
description: PowerDNS recursive DNS resolver with DNSSEC validation
type: application
version: 0.1.14
home: https://www.powerdns.com/recursor/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=powerdns/pdns-recursor-53
appVersion: '5.3.6'
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
