apiVersion: v2
name: powerdns-recursor
description: A Helm chart for Kubernetes
type: application
version: 0.1.8
# renovate: image=powerdns/pdns-recursor-53
appVersion: '5.3.4'
dependencies:
  - name: common
    version: 4.6.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
