apiVersion: v2
name: arr-stack
description: A Helm chart for the *arr stack (Sonarr, Radarr, Prowlarr, etc.)
type: application
version: 0.2.6
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
