apiVersion: v2
name: arr-stack
description: Media automation stack with Sonarr, Radarr, Prowlarr, Bazarr, Flaresolverr, Configarr, and UmlautAdaptarr
type: application
version: 0.10.6
home: https://wiki.servarr.com/
sources:
  - https://github.com/swagner-de/charts
dependencies:
  - name: common
    version: 5.1.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
