sonarr:
  enabled: true
  port: 8989
  image:
    repository: ghcr.io/home-operations/sonarr
    tag: '4.0.17.2953'
  persistence:
    config:
      type: persistentVolumeClaim
      mountPath: /config
      size: 100Mi
      # storageClass: "gp2"
      accessMode: ReadWriteOnce

radarr:
  enabled: true
  port: 7878
  image:
    repository: ghcr.io/home-operations/radarr
    tag: '6.1.2'
  persistence:
    config:
      type: persistentVolumeClaim
      mountPath: /config
      size: 100Mi
      # storageClass: "gp2"
      accessMode: ReadWriteOnce

prowlarr:
  enabled: true
  port: 9696
  image:
    repository: ghcr.io/home-operations/prowlarr
    tag: '2.3.5.5318'
  persistence:
    config:
      type: persistentVolumeClaim
      mountPath: /config
      size: 100Mi
      accessMode: ReadWriteOnce
      # storageClass: "gp2"

flaresolverr:
  enabled: true
  port: 8191
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: 'v3.4.6'

bazarr:
  enabled: true
  port: 6767
  image:
    repository: ghcr.io/home-operations/bazarr
    tag: '1.5.6'
  persistence:
    config:
      type: persistentVolumeClaim
      mountPath: /config
      size: 100Mi
      # storageClass: "gp2"
      accessMode: ReadWriteOnce

configarr:
  enabled: false
  persistence:
    cache:
      type: emptyDir
      size: 100Mi
      # storageClass: "gp2"
      accessMode: ReadWriteOnce
  config: |
    trashGuideUrl: https://github.com/TRaSH-Guides/Guides
    recyclarrConfigUrl: https://github.com/recyclarr/config-templates

    sonarr:
      series:
        base_url: http://sonarr:8989
        api_key: !secret SONARR_API_KEY

        quality_definition:
          type: series

        include:
          # WEB-1080p
          - template: sonarr-quality-definition-series
          - template: sonarr-v4-quality-profile-web-1080p
          - template: sonarr-v4-custom-formats-web-1080p

          # WEB-2160p
          - template: sonarr-v4-quality-profile-web-2160p
          - template: sonarr-v4-custom-formats-web-2160p

        custom_formats: []
    radarr: {}

  secrets:
    existingSecret: ""
    data: {}
      # SONARR_API_KEY: 1234
