apiVersion: v2
name: powerdns-auth
description: PowerDNS authoritative DNS server with LMDB backend and external-dns support
type: application
version: 0.4.1
home: https://www.powerdns.com/auth/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=powerdns/pdns-auth-50
appVersion: '5.0.3'
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
