apiVersion: v2
name: adguard-home
description: DNS-level ad and tracker blocking with optional Prometheus exporter
type: application
version: 0.6.3
home: https://github.com/AdguardTeam/AdGuardHome
sources:
  - https://github.com/swagner-de/charts
# renovate: image=11notes/adguard
appVersion: '0.107.74'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
