# -- Persistent storage configuration
persistence:
  # -- Configuration volume
  config:
    # -- Enable persistent storage for config
    enabled: true
    # storageClass: my-storage-class
    # -- Storage access mode
    accessMode: ReadWriteOnce
    # -- Volume size
    size: 4Gi

  # -- Data volume
  data:
    # -- Enable persistent storage for data
    enabled: true
    # storageClass: my-storage-class
    # -- Storage access mode
    accessMode: ReadWriteOnce
    # -- Volume size
    size: 4Gi

  # -- TLS certificate volume
  certs:
    # -- Enable TLS certificate mount from a Secret
    enabled: false
    # enabled: true
    # type: secret
    # name: adguard-tls
    # advancedMounts:
    #   main:
    #     main:
    #     - path: /certs/

# service: {}
# main:
#   type: LoadBalancer
#   externalTrafficPolicy: Local
#   ipFamilyPolicy: PreferDualStack
#   annotations:
#     metallb.universe.tf/loadBalancerIPs: "10.10.10.10"

# ingress:
# main:
#   enabled: true
#   annotations:
#     cert-manager.io/cluster-issuer: lets-encrypt-prod
#   hosts:
#     - host: adguard.mydomain.com
#       paths:
#       - path: /
#         pathType: Prefix
#         service:
#           identifier: main
#           port: http
#   tls:
#     - secretName: adguard-tls
#       hosts:
#         - adguard.mydomain.com

# controllers:
#   main:
#     containers:
#       main:
#         resources:
#           requests:
#             cpu: 100m
#             memory: 100Mi


# -- Prometheus ServiceMonitor configuration
serviceMonitor:
  main:
    # -- Enable Prometheus ServiceMonitor
    enabled: false
