{{- define "hardcoded" -}}
global:
  alwaysAppendIdentifierToResourceName: true

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    initContainers:
      init:
        enabled: {{ .Values.cnpg.enabled }}
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image:
          repository: alpine
          tag: 3.23.4
        command: ["sh"]
        envFrom:
          - secret: {{ .Values.cnpg.clusterName }}-app
        args:
        - -c
        - |
            if [ -f /config/configuration.yaml ]; then
              sed -i "/db_url:/c\  db_url: postgresql://$username:$password@$host/$dbname?sslmode=verify-full&sslrootcert=/certs/ca.crt" /config/configuration.yaml
            fi
    containers:
      ldap:
        name: ldap
        image:
          repository: ghcr.io/swagner-de/home-assistant-ldap-helper
          tag: v0.3.0
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            identifier: ldap
        - secretRef:
{{- if .Values.ldapSecret }}
            name: {{ .Values.ldapSecret }}
{{- else }}
            identifier: ldap
{{- end }}
        args:
        - run-server
      main:
        name: homeassistant
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: {{ .Chart.AppVersion | quote }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 500m
            memory: 400Mi
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                port: 8123
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe
          startup: *probe
  matterbridge:
    enabled: {{ .Values.matterbridge.enabled | default false }}
    containers:
      main:
        name: matterbridge
        image:
          repository: luligu/matterbridge
          tag: 3.7.3
        command: /matterbridge-init/matterbridge-init.sh
        env:
          - name: POD_IPS
            valueFrom:
              fieldRef:
                fieldPath: status.podIPs
          - name: MDNS_INTERFACE
            value: {{ .Values.matterbridge.mdns_interface }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
            add:
            - NET_RAW 
persistence:
  config:
    type: persistentVolumeClaim
    advancedMounts:
      main:
        main:
          - path: /config
        init:
          - path: /config
  matterbridge:
    enabled: {{ .Values.matterbridge.enabled | default false }}
    type: persistentVolumeClaim
    advancedMounts:
      matterbridge:
        main:
          - path: /nonexistent
  
  matterbridge-init:
    enabled: {{ .Values.matterbridge.enabled | default false }}
    type: configMap
    defaultMode: 0755
    identifier: matterbridge-init
    advancedMounts:
      matterbridge:
        main:
          - path: /matterbridge-init

  tmp:
    type: emptyDir
    advancedMounts:
      main:
        main:
        - path: /tmp
{{ if .Values.cnpg.enabled }}
  certs:
    type: secret
    name: {{ .Values.cnpg.clusterName }}-ca
    advancedMounts:
      main:
        main:
        - path: /certs/ca.crt
          subPath: ca.crt
{{ end }}


configMaps:

  ldap:
    enabled: {{ .Values.controllers.main.containers.ldap.enabled }}
    data: {{ toYaml .Values.ldap  | nindent 6 }}

  matterbridge-init:
    enabled: {{ .Values.matterbridge.enabled | default false }}
    data:
      matterbridge-init.sh: |
        #!/bin/sh
        set -e

        IPV4=""
        IPV6=""

        # Split on commas
        IFS=',' read -r IP1 IP2 <<EOF
        $POD_IPS
        EOF

        for ip in "$IP1" "$IP2"; do
          case "$ip" in
            *:*) IPV6="$ip" ;;
            *.*) IPV4="$ip" ;;
          esac
        done

        ARGS="
        --logger debug
        --mdnsinterface $MDNS_INTERFACE
        "

        #[ -n "$IPV4" ] && ARGS="$ARGS --ipv4address $IPV4"
        #[ -n "$IPV6" ] && ARGS="$ARGS --ipv6address $IPV6"

        echo "Starting matterbridge with args:"
        echo "$ARGS"

        exec /usr/local/bin/matterbridge $ARGS

service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8123
        protocol: TCP
  matterbridge:
    enabled: {{ .Values.matterbridge.enabled | default false }}
    controller: matterbridge
    ports:
      http:
        port: 8283
        protocol: TCP

rbac:
  roles: {}

{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
