{{- define "hardcoded" -}}
global:
  alwaysAppendIdentifierToResourceName: true

defaultPodOptions:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    initContainers:
      init:
        enabled: {{ .Values.cnpg.enabled }}
        securityContext:
          capabilities:
            drop:
            - ALL
        image:
          repository: alpine
          tag: 3.22.1
        command: ["sh"]
        envFrom:
          - secret: {{ .Values.cnpg.clusterName }}-app
        args:
        - -c
        - |
            if [ -f /config/configuration.yaml ]; then
              sed -i "/db_url:/c\  db_url: postgresql://$username:$password@$host/$dbname?sslmode=verify-full&sslrootcert=/certs/ca.crt" /config/configuration.yaml
            fi
    containers:
      ldap:
        name: ldap
        image:
          repository: ghcr.io/swagner-de/home-assistant-ldap-helper
          tag: v0.3.0
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            identifier: ldap
        - secretRef:
{{- if .Values.ldapSecret }}
            name: {{ .Values.ldapSecret }}
{{- else }}
            identifier: ldap
{{- end }}
        args:
        - run-server
      main:
        name: homeassistant
        image:
          repository: ghcr.io/home-operations/home-assistant
          tag: {{ .Chart.AppVersion | quote }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        resources:
          requests:
            cpu: 500m
            memory: 400Mi
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                port: 8123
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probe
          startup: *probe
  matterhub:
    enabled: {{ .Values.matterHub.enabled | default false }}
    containers:
      main:
        name: matterhub
        image:
          repository: ghcr.io/t0bst4r/home-assistant-matter-hub
          tag: 3.0.2
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        env:
          - name: HAMH_HOME_ASSISTANT_URL
            value: "http://{{ .Release.Name }}-main:8123/"
          - name: HAMH_HOME_ASSISTANT_ACCESS_TOKEN
{{- if .Values.matterHub.existingSecret }}
            valueFrom:
              secretKeyRef:
                name: {{ .Values.matterHub.existingSecret.name }}
                key: {{ .Values.matterHub.existingSecret.key }}
{{- end }}
          - name: HAMH_LOG_LEVEL
            value: {{ .Values.matterHub.logLevel | default "info" }}
          - name: HAMH_HTTP_PORT
            value: "8482"
{{- if not .Values.matterHub.existingSecret.name  }}
        envFrom:
          - secretRef:
              name: matterHub
{{- end }}

persistence:
  config:
    type: persistentVolumeClaim
    advancedMounts:
      main:
        main:
          - path: /config
        init:
          - path: /config
  matterhub:
    enabled: {{ .Values.matterHub.enabled | default false }}
    type: persistentVolumeClaim
    advancedMounts:
      matterhub:
        main:
          - path: /data

  tmp:
    type: emptyDir
    advancedMounts:
      main:
        main:
        - path: /tmp
{{ if .Values.cnpg.enabled }}
  certs:
    type: secret
    name: {{ .Values.cnpg.clusterName }}-ca
    advancedMounts:
      main:
        main:
        - path: /certs/ca.crt
          subPath: ca.crt
{{ end }}


configMaps:

  ldap:
    enabled: {{ .Values.controllers.main.containers.ldap.enabled }}
    data: {{ toYaml .Values.ldap  | nindent 6 }}



service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8123
        protocol: TCP
  matterhub:
    enabled: {{ .Values.matterHub.enabled | default false }}
    controller: matterhub
    ports:
      http:
        port: 8482
        protocol: TCP



rbac:
  roles: {}

{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
