apiVersion: v2
name: netra
description: ASN traffic analysis dashboard for NetFlow/IPFIX flow data
type: application
version: 0.1.1
home: https://github.com/consi/netra
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/consi/netra
appVersion: '1.0.8'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
