apiVersion: v2
name: invidious
description: Invidious + inv-sig-helper + Postgres, based on bjw-s common chart
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
version: 0.3.11
# renovate: image=quay.io/invidious/invidious
appVersion: '2.20250913.0'
keywords:
  - invidious
  - youtube
  - postgres
home: https://github.com/iv-org/invidious
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.2
  - name: postgres
    repository: oci://registry-1.docker.io/cloudpirates
    version: 0.15.1
    condition: postgres.enabled
