{{- define "hardcoded" -}}
{{- $servers := list "sonarr" "radarr" "prowlarr" "bazarr" "flaresolverr" -}}

global:
  createDefaultServiceAccount: false

# Configure options applied to all pods
defaultPodOptions:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

controllers:
{{- range $server := $servers }}
{{- $serverConfig := get $.Values $server }}
{{- if $serverConfig.enabled | default false }}
  {{ $server }}:
    enabled: true
{{- if eq $server "flaresolverr" }}
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
{{- end }}
    containers:
      main:
        image: {{ $serverConfig.image | toYaml | nindent 12 }}
        securityContext:
{{- if ne $server "flaresolverr" }}
          readOnlyRootFilesystem: true
{{- end }}
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        probes:
          liveness: &{{ $server }}Probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: {{ $serverConfig.port }}
              initialDelaySeconds: 10
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 3
          readiness: *{{ $server }}Probe
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: {{ $serverConfig.port }}
              initialDelaySeconds: 5
              periodSeconds: 5
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 30
{{- end }}
{{- end }}

  configarr:
    enabled: {{ .Values.configarr.enabled }}
    type: cronjob
    containers:
      main:
        image: {{ $.Values.configarr.image | toYaml | nindent 12 }}
        envFrom:
{{- if .Values.configarr.secrets.existingSecret }}
          - secret: {{ .Values.configarr.secrets.existingSecret }}
{{- end }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
    cronjob:
      schedule: "0 * * * *" 

service:
{{- range $server := $servers }}
{{- $serverConfig := get $.Values $server }}
{{- if $serverConfig.enabled | default false }}
  {{ $server }}:
    type: ClusterIP
    controller: {{ $server }}
    ports:
      http:
        port: {{ $serverConfig.port }}
{{- end }}
{{- end }}


persistence:
{{- range $server := $servers }}
{{- $serverConfig := get $.Values $server }}
{{- if $serverConfig.enabled | default false }}
{{- range $pName, $pConfig := $serverConfig.persistence }}
  {{ printf "%s-%s" $server $pName}}: 
    enabled: true
{{ (omit (omit $pConfig "mountPath" "subPath")) | toYaml | indent 4 }}
    advancedMounts:
      {{ $server }}:
        main:
          - path: {{ $pConfig.mountPath }}
{{- if (hasKey $pConfig "subPath") }}
            subPath: {{ $pConfig.subPath }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}

  configarr-cache:
    enabled: {{ .Values.configarr.enabled }}
    type: {{ .Values.configarr.persistence.cache.type }}
    size: {{ .Values.configarr.persistence.cache.size }}
    accessMode: {{ .Values.configarr.persistence.cache.accessMode }}
{{- if .Values.configarr.persistence.cache.storageClass }}
    storageClass: {{ .Values.configarr.persistence.cache.storageClass }}
{{- end }}
    advancedMounts:
      configarr:
        main:
          - path: /app/repos
  configarr-config:
    type: configMap
    enabled: {{ .Values.configarr.enabled }}
    identifier: configarr
    advancedMounts:
      configarr:
        main:
        - path: /app/config/config.yml
          subPath: config.yml
  configarr-secrets:
    type: secret
    enabled: {{ ( and .Values.configarr.enabled (.Values.configarr.secrets.data | len  )) }}
{{- if ( and .Values.configarr.enabled (.Values.configarr.secrets.data | len  )) }}
    identifier: configarr
    advancedMounts:
      configarr:
        main:
        - path: /app/config/secrets.yml
          subPath: secrets.yml
{{- end }}

configMaps:
  configarr:
    enabled: {{ .Values.configarr.enabled }}
    data:
      config.yml: |
{{ .Values.configarr.config | indent 10 }}

secrets:
  configarr:
    enabled: {{ and .Values.configarr.enabled (.Values.configarr.secrets.data | len  )}}
    stringData: {{ .Values.configarr.secrets.data | toYaml | nindent 10}}



{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
