apiVersion: v2
name: zigbee2mqtt
description: A chart installing zigbee2mqtt
type: application
version: 0.5.0
# renovate: image=koenkk/zigbee2mqtt
appVersion: '2.7.2'
dependencies:
  - name: common
    version: 4.6.0
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
