apiVersion: v2
name: immich
version: 0.12.5
description: Self-hosted photo and video backup solution with machine learning
type: application
home: https://immich.app/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/immich-app/immich-server
appVersion: 'v2.7.5'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: redis
    version: 0.30.5
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
