apiVersion: v2
name: immich
version: 0.4.5
description: This is the Helm chart for Immich, a self-hosted photo and video backup solution.
type: application
# renovate: image=ghcr.io/immich-app/immich-server
appVersion: 'v2.5.6'
dependencies:
  - name: common
    version: 4.6.2
    repository: https://bjw-s-labs.github.io/helm-charts/
  - name: redis
    version: 0.25.5
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
