apiVersion: v2
name: splitpro
description: SplitPro — self-hosted open source alternative to Splitwise for sharing expenses
type: application
version: 0.2.0
# renovate: image=ghcr.io/oss-apps/splitpro
appVersion: "v2.1.5"
sources:
  - https://github.com/swagner-de/charts
  - https://github.com/oss-apps/split-pro
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
dependencies:
  - name: common
    version: 5.2.1
    repository: https://bjw-s-labs.github.io/helm-charts/
