apiVersion: v2
name: carconnectivity
description: Car telemetry data retrieval with plugin support (VW, ABRP, WebUI)
type: application
version: 0.2.0
home: https://github.com/tillsteinbach/CarConnectivity
sources:
  - https://github.com/swagner-de/charts
# renovate: image=ghcr.io/swagner-de/containers/carconnectivity
appVersion: '0.11.10'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
