{{- define "hardcoded" -}}

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534
    fsGroupChangePolicy: OnRootMismatch

controllers:
  main:
    containers:
      main:
        enabled: true
        securityContext:
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
            - ALL
        image:
          repository: ghcr.io/consi/flowcus
          tag: {{ .Chart.AppVersion | quote }}
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 2137
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 5
              successThreshold: 1
              failureThreshold: 3
          readiness: *probe
          startup: *probe

service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 2137
        protocol: TCP
  netflow:
    controller: main
    primary: true
    ports:
      netflow:
        port: 4739
        protocol: UDP

ingress:
  main:
    enabled: false

persistence:
  data:
    type: persistentVolumeClaim
    advancedMounts:
      main:
        main:
        - path: /data/storage

{{ end }}

{{- $ctx := deepCopy . -}}
{{- $_ := include "hardcoded" . | fromYaml | mergeOverwrite $ctx.Values -}}

{{ include "bjw-s.common.loader.all" $ctx }}
