apiVersion: v2
name: freeradius
description: FreeRADIUS server with LDAP backend for WPA Enterprise and MAC authentication
type: application
version: 0.1.0
home: https://freeradius.org/
sources:
  - https://github.com/swagner-de/charts
# renovate: image=freeradius/freeradius-server
appVersion: '3.2.7'
dependencies:
  - name: common
    version: 5.0.1
    repository: https://bjw-s-labs.github.io/helm-charts/
maintainers:
  - name: swagner-de
    email: swagner-de@users.noreply.github.com
